name = "CausalDiscovery"
uuid = "d351d3f1-f7cd-4969-9389-1799ca719ed5"
authors = ["Zenna Tavares"]
version = "0.1.0"

[deps]
Autumn = "1149b079-14b7-44b1-a7c1-de8e2f6b625a"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ImageInTerminal = "d8c32880-2388-543b-8c61-d9f865259254"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Rematch = "bfecab0d-fd4d-5014-a23f-56c5fae6447a"
SExpressions = "eaa8e424-c5f6-11e8-1b3d-d576ba0eee97"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
